### PR TITLE
fix race condition

### LINKED ISSUE #13: Race condition between reaper and command
I observe that sometime `secrets-init` logs a message `level=error msg="failed to wait for command to complete" error="waitid: no child processes"` and exits with an error code.

This appears to be because sometimes the subprocess started by `exec.Command` is reaped by `syscall.Wait4` before `cmd.Wait` reaps it.

I think an alternative implementation could not use `cmd.Wait` and instead let `syscall.Wait4` reap all children, as done by [tini](https://github.com/krallin/tini/blob/master/src/tini.c).

In addition, I think it would be more useful to return the return code from the subprocess instead of always exiting with code 1 on error.

I hope this is useful! Thanks for the tool.

### PR DESCRIPTION
**Pull request by aclowes**
wait4 and cmd.wait would wait on the child process, and an error was thrown if wait4 got it first. Instead, remove the cmd.wait and use only wait4. Fixes  #13.

Also:
- capture and exit with the child process return code
- don't sleep between wait4 calls, let wait4 block for us.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -127,47 +121,50 @@ func mainCmd(c *cli.Context) error {
...
-		default:
-		}
 	}
+	// no more children, exit with the same code as the child process
+	os.Exit(exitCode)
 }
 
 // run passed command
-func run(ctx context.Context, provider secrets.Provider, commandSlice []string) error {
+func run(ctx context.Context, provider secrets.Provider, commandSlice []string, childPid *int) error {
```
Comment (alexei-led) [inline main.go]: Please use `return` to return child PID from the function and not as a reference to the parameter.

File: main.go [hunk 2]
```diff
@@ -127,47 +121,50 @@ func mainCmd(c *cli.Context) error {
...
 
-func removeZombies(ctx context.Context, wg *sync.WaitGroup) {
+func removeZombies(childPid int) {
+	var exitCode int
 	for {
 		var status syscall.WaitStatus
 
 		// wait for an orphaned zombie process
-		pid, _ := syscall.Wait4(-1, &status, syscall.WNOHANG, nil)
+		pid, err := syscall.Wait4(-1, &status, 0, nil)
```
Comment (alexei-led) [inline main.go]: why to replace `syscall.WNOHANG` with `0`?

File: main.go [hunk 3]
```diff
@@ -127,47 +121,50 @@ func mainCmd(c *cli.Context) error {
...
+			log.WithError(err).Error("unexpected wait4 error")
+			os.Exit(1)
 		} else {
+			// check if pid is child, if so save
 			// PID is > 0 if a child was reaped and we immediately check if another one is waiting
+			if pid == childPid {
+				exitCode = status.ExitStatus()
+			}
 			continue
 		}
```
Comment (alexei-led) [inline main.go:160]: why non-blocking test removed? can you, please, explain

**Review by alexei-led — CHANGES_REQUESTED** [review]
@aclowes thank you for the PR. I would like to better understand these changes

File: main.go (hunk 1 above)
Comment (aclowes) [reply main.go]: Changed. I used named return values; I'm not sure if this is appropriate.

File: main.go (hunk 2 above)
Comment (aclowes) [reply main.go]: WNOHANG returns immediately. Zero waits until there is a process to reap. This change makes the code more efficient, instead of running in a busy loop it waits for the next event.

File: main.go (hunk 3 above)
Comment (aclowes) [reply main.go:160]: I removed the WaitGroup and context because we are no longer waiting for the child process in a separate routine - instead, all processes (the child and any grandchildren) are reaped in this loop.

Comment (alexei-led) [reply main.go:160]: ok

**Comment by aclowes** [comment]
@alexei-led I've fixed the link error, would you please re-run the workflow? Thanks.
